// EventTap.swift — Suppresses original BoDial scroll events.
//
// macOS generates scroll events from the BoDial's HID reports at a driver
// level we can't intercept. Instead, we suppress those events here and let
// DeviceMonitor inject replacement events with proper scaling.
//
// We identify BoDial-originated events using the DeviceMonitor's report
// timestamps — if a scroll event arrives within 10ms of a BoDial HID report,
// it came from the BoDial. Our own injected events carry a marker in
// eventSourceUserData so we pass them through.

import CoreGraphics
import Foundation
import os

class ScrollEventTap {
    fileprivate var machPort: CFMachPort?
    private var runLoopSource: CFRunLoopSource?
    private weak var deviceMonitor: DeviceMonitor?

    init(deviceMonitor: DeviceMonitor) {
        self.deviceMonitor = deviceMonitor
    }

    func start() -> Bool {
        log.notice("EventTap.start: creating cghidEventTap for scrollWheel events")
        let eventMask: CGEventMask = (1 << CGEventType.scrollWheel.rawValue)

        let context = TapContext(tap: self, monitor: deviceMonitor!)
        let contextPtr = Unmanaged.passRetained(context).toOpaque()

        guard let tap = CGEvent.tapCreate(
            tap: .cghidEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: eventMask,
            callback: scrollCallback,
            userInfo: contextPtr
        ) else {
            log.error("Failed to create event tap — Accessibility permission may be missing")
            return false
        }

        self.machPort = tap
        CGEvent.tapEnable(tap: tap, enable: true)

        let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
        self.runLoopSource = source
        CFRunLoopAddSource(CFRunLoopGetCurrent(), source, .defaultMode)

        log.notice("EventTap.start: tap installed")
        return true
    }

    func stop() {
        guard machPort != nil else {
            log.notice("EventTap.stop: already stopped")
            return
        }
        log.notice("EventTap.stop: disabling and invalidating tap")
        if let tap = machPort {
            CGEvent.tapEnable(tap: tap, enable: false)
        }
        if let source = runLoopSource {
            CFRunLoopRemoveSource(CFRunLoopGetCurrent(), source, .defaultMode)
        }
        // CFMachPort is invalidated when its last reference drops; explicit invalidate
        // ensures the kernel-side tap is torn down before the process exits, so a
        // rapid relaunch doesn't race against a still-live tap.
        if let tap = machPort {
            CFMachPortInvalidate(tap)
        }
        runLoopSource = nil
        machPort = nil
        log.notice("EventTap.stop: tap torn down")
    }
}

private class TapContext {
    let tap: ScrollEventTap
    let monitor: DeviceMonitor
    init(tap: ScrollEventTap, monitor: DeviceMonitor) {
        self.tap = tap
        self.monitor = monitor
    }
}

private func scrollCallback(
    proxy: CGEventTapProxy,
    type: CGEventType,
    event: CGEvent,
    userInfo: UnsafeMutableRawPointer?
) -> Unmanaged<CGEvent>? {

    if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
        let reason = type == .tapDisabledByTimeout ? "timeout" : "userInput"
        log.notice("EventTap: tap disabled (\(reason, privacy: .public)), re-enabling")
        if let info = userInfo {
            let context = Unmanaged<TapContext>.fromOpaque(info).takeUnretainedValue()
            if let port = context.tap.machPort {
                CGEvent.tapEnable(tap: port, enable: true)
            }
        }
        return Unmanaged.passUnretained(event)
    }

    guard let info = userInfo else {
        return Unmanaged.passUnretained(event)
    }

    let context = Unmanaged<TapContext>.fromOpaque(info).takeUnretainedValue()

    // If the BoDial recently sent a HID report, this scroll event was
    // generated by the BoDial's OS driver. Scale it in-place and pass it
    // through. The monitor's applyScaling() is a no-op at 100%, so at
    // maximum sensitivity the device's own feel reaches apps untouched.
    if context.monitor.recentlyReceivedReport() {
        context.monitor.applyScaling(to: event)
        return Unmanaged.passUnretained(event)
    }

    // Not from the BoDial — pass through (trackpad, other mice, etc.)
    return Unmanaged.passUnretained(event)
}
